title: "Dapy: a simple framework for simulating distributed algorithms in python."

description: "This python package is aims at prototyping distributed algorithms
    and execute them in a simulated environment. The main (and only) intended aim
    of this framework is as a support for teaching classes on distributed algorithms
    and to provide a context for experimenting with such algorithms."

baseurl: "/dapy"
